// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCADvqhhIrLEG75QtJ2o004DAUhFjhsk0',
    appId: '1:352792412991:web:c82db765a935cbef30c98a',
    messagingSenderId: '352792412991',
    projectId: 'creatoo-2b4b1',
    authDomain: 'creatoo-2b4b1.firebaseapp.com',
    storageBucket: 'creatoo-2b4b1.appspot.com',
    measurementId: 'G-YYNLQMQ4NS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaS0ZrqQdQgv8DonaOTEuhJ8V2PPwM33I',
    appId: '1:352792412991:android:a368356d188ff34930c98a',
    messagingSenderId: '352792412991',
    projectId: 'creatoo-2b4b1',
    storageBucket: 'creatoo-2b4b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCX8kTQyzTPuWW2jysLuc-pSnht-UfXgTA',
    appId: '1:352792412991:ios:40f8e50e2d7f595a30c98a',
    messagingSenderId: '352792412991',
    projectId: 'creatoo-2b4b1',
    storageBucket: 'creatoo-2b4b1.appspot.com',
    iosBundleId: 'com.creatoo.creatooapp',
  );
}
